---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflask
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: myflask
        image: sinansaritr/myflask:latest
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-pw
        ports:
        - containerPort: 3000
          name: flask-container
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: myflask
  labels:
    app: flask
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: flask
    targetPort: 3000
    nodePort: 30000
  selector:
    app: flask
  type: NodePort
