apiVersion: v1
kind: Service
metadata:
  name: hello-devops
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-devops
spec:
  selector:
    matchLabels:
      app: hello-devops
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-devops
    spec:
      containers:
      - name: hello-devops
        image: hello-devops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000